import type { SafeSupportContext, SupportAnswer, SupportRole, SupportTopic } from './support.types.js';
export const UNKNOWN = "I don't have enough information to confirm that.";
export const KNOWLEDGE: { id: string; roles: SupportRole[]; title: string; content: string }[] = [
    { id: 'orders', roles: ['customer', 'seller'], title: 'Home Delivery orders', content: 'Home Delivery follows Order Placed → Processing → Shipped → Out for Delivery → Delivered. COD starts Processing after successful creation; online orders start Processing only after verified payment. Order Placed stays as the first timeline step. Pending/placed/confirmed are older Order Placed labels.' },
    { id: 'delivery', roles: ['customer'], title: 'Delivery help', content: 'Track your order in My Orders → Order Details. Delivery is supported in Akola, Maharashtra, PIN codes 444001 and 444002. Eligible orders may receive same-day delivery; no exact arrival time is guaranteed by Help.' },
    { id: 'shipping-labels', roles: ['seller'], title: 'Shipping labels and delivery scans', content: 'Processing starts automatically. Open Order Details → Generate Shipping Label. Only after label generation succeeds does the order become Shipped and open Delivery. In Delivery, scan the order label to mark Out for Delivery. A second scan allows Delivered. Confirm each action; Help cannot change the order. A product/SKU barcode is not a shipping label. Refunded/cancelled items cannot be dispatched.' },
    { id: 'pickup', roles: ['customer', 'seller'], title: 'Store Pickup reservations', content: 'Store Pickup follows Reserved → Ready → Picked Up, or Expired/Cancelled. Reservations last 2 hours. The QR is valid only for an active reservation, and does not extend the expiry. Use Pay Online or Pay at Store; the seller records cash collection for Pay at Store at pickup. After expiry, use Reserve Again if currently available. Expired paid reservations may require refund handling; do not assume a refund completed.' },
    { id: 'pickup-availability', roles: ['customer', 'seller'], title: 'Pickup availability', content: 'Pickup requires one eligible seller, available products, pickup enabled and a complete store pickup address. The store must be open with at least 2 hours before closing. Seller hours, weekly closed days, temporary closures and special closure dates control availability. Multi-seller carts cannot reserve Store Pickup. Existing reservations retain their original deadline and QR when a schedule changes.' },
    { id: 'pickup-settings', roles: ['seller'], title: 'Pickup schedule settings', content: 'Open Seller Profile → Store Pickup settings. Enable pickup, complete the store address and configure weekly hours, weekly closed days, special closure dates and temporary closure. Use Asia/Kolkata time; enabled days need at least 2 hours and overnight hours are unsupported. A schedule change does not automatically cancel an existing reservation.' },
    { id: 'payment', roles: ['customer', 'seller'], title: 'Payment statuses', content: 'Pending means payment is not confirmed; Failed means an attempt failed; Success means backend confirmation or recorded cash collection. COD/Pay at Store may stay Pending until cash is collected. For Home Delivery online payment, use the payment retry option and remaining time shown in the order. Help cannot confirm a bank debit from a message or collect payment credentials.' },
    { id: 'cancellation', roles: ['customer', 'seller'], title: 'Cancellation', content: 'For Home Delivery, use Cancel Order or item cancellation in Order Details before shipping, when the app offers it. Store Pickup uses its own cancellation actions while a reservation is active. Help cannot cancel on your behalf. Paid cancellation refund status must be checked in Order Details.' },
    { id: 'refunds', roles: ['customer', 'seller'], title: 'Returns, replacements and refunds', content: 'ECSLocal products are non-returnable after delivery for a refund. Eligible products can request replacement within 3 days of delivery, subject to the current Replacement Policy and eligibility shown in Order Details. Refund Pending/Required does not mean completed; only Processed confirms completion. Never promise an approval, refund amount or date without verified context. Escalate disputes to human support.' },
    { id: 'settlements', roles: ['seller'], title: 'Payments and settlements', content: 'Check Seller Payments for current earnings, payout status and bank verification. COD is manually collected and is not an online bank earning. Online settlement eligibility depends on backend configuration and the earning/payout shown in Payments. Do not promise settlement amounts or dates. Create a support ticket for a missing payout or settlement dispute; never share bank credentials in chat.' },
    { id: 'products', roles: ['seller'], title: 'Products and inventory', content: 'Use Inventory/Products to add or edit products, prices, photos, variants and stock. Verify the selected variant and its child size/shade stock. Reserved/ordered products affect stock; cancellation/expiry restores eligible remaining quantities through existing order rules. Help cannot edit inventory.' },
    { id: 'account', roles: ['customer', 'seller'], title: 'Account help', content: 'Use Profile to manage account details and the existing Forgot Password/Forgot Email flows to recover access. Never share passwords, OTPs, card PINs, authentication tokens or private keys. Create a support ticket for an account-access or store-settings problem you cannot resolve.' },
];
const LABELS: Record<string, string> = { pending: 'Order Placed', placed: 'Order Placed', confirmed: 'Order Placed', processing: 'Processing', shipped: 'Shipped', out_for_delivery: 'Out for Delivery', delivered: 'Delivered', cancelled: 'Cancelled', partially_cancelled: 'Partially Cancelled', reserved: 'Reserved', ready: 'Ready', picked_up: 'Picked Up', expired: 'Expired', success: 'Successful', failed: 'Failed', processed: 'Processed', none: 'None recorded', pay_at_store: 'Pay at Store', cod: 'Cash on Delivery', online: 'Online', razorpay: 'Online' };
const label = (value: string) => LABELS[value.toLowerCase()] || 'Unknown';
export function contextAnswer(topic: SupportTopic, context: SafeSupportContext): string {
    const o = context.order;
    if (topic === 'pickup') {
        const store = context.store ? 'Current store pickup: ' + (context.store.pickupAvailable ? 'available during ' + context.store.hoursLabel : context.store.pickupReason) + '. ' : '';
        if (!o) return store + (context.role === 'customer' ? 'Open Help from Order Details for reservation-specific information.' : 'Check your current Store Pickup settings.');
        if (o.fulfillmentType !== 'pickup') return 'The selected order is Home Delivery, not Store Pickup. ' + store;
        return 'This reservation is ' + label(o.pickupStatus || '') + '.' + (o.reservationElapsed && ['reserved', 'ready'].includes(o.pickupStatus || '') ? ' Its reservation deadline has elapsed; refresh Order Details to confirm expiry.' : '') + (o.pickupExpiresAt ? ' Reservation deadline: ' + new Date(o.pickupExpiresAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) + ' IST.' : '') + (o.refundRequired ? ' Refund handling is required; completion is not confirmed by this flag.' : '') + ' ' + store;
    }
    if (!o) return UNKNOWN + ' Open Help from Order Details for the current order status, or contact support.';
    if (topic === 'payment') return 'Recorded payment status: ' + label(o.paymentStatus) + '. Payment method: ' + label(o.paymentMethod) + '. ' + (o.paymentStatus !== 'success' ? 'This does not confirm an online payment was received.' : '');
    if (topic === 'refund') return 'Recorded refund status: ' + label(o.refundStatus) + '.' + (o.itemRefundStatuses?.length ? ' Item refund statuses: ' + o.itemRefundStatuses.map(label).join(', ') + '.' : '') + (o.refundRequired ? ' This pickup requires refund handling.' : '') + (o.refundStatus !== 'processed' ? ' A completed refund is not confirmed.' : ' This describes the recorded refund, not an approval for additional refunds.');
    return 'Order #' + o.reference + ': ' + label(o.fulfillmentType === 'pickup' ? o.pickupStatus || '' : o.status) + '.' + (o.fulfillmentType === 'pickup' ? ' This is Store Pickup.' : ' This is Home Delivery.');
}
export function renderAnswer(ids: string[], topic: SupportTopic, context: SafeSupportContext, needsHuman = false, source: 'knowledge' | 'ai' = 'knowledge'): SupportAnswer {
    const relevantIds = context.order?.fulfillmentType === 'pickup' ? ids.map(id => id === 'orders' ? 'pickup' : id) : ids;
    const entries = KNOWLEDGE.filter(k => relevantIds.includes(k.id) && k.roles.includes(context.role)).slice(0, 2);
    const insufficient = !entries.length || (topic !== 'none' && topic !== 'pickup' && !context.order);
    const text = [topic !== 'none' ? contextAnswer(topic, context) : '', ...entries.map(k => k.content)].filter(Boolean).join('\n\n');
    return { message: (text || UNKNOWN) + (needsHuman || insufficient ? '\n\nContact Support to create a ticket for human review.' : ''), needsHuman: needsHuman || insufficient, source,
        suggestedActions: [...(context.order ? ['view_order' as const] : []), ...(context.role === 'seller' && ids.includes('pickup-settings') ? ['pickup_settings' as const] : []), 'contact_support'] };
}
export function commonAnswer(message: string, context: SafeSupportContext): SupportAnswer | undefined {
    const q = message.toLowerCase().replace(/[?!.]/g, '').trim();
    if (/fraud|scam|dispute|wrong (?:order|item)|charged twice|missing payout|unauthori[sz]ed|cannot (?:log|sign) in|can't (?:log|sign) in/.test(q)) return renderAnswer([], /refund/.test(q) ? 'refund' : /pay|charged/.test(q) ? 'payment' : 'none', context, true);
    const exact: Record<string, [string[], SupportTopic]> = {
        'where is my order': [['orders'], 'order'], 'order help': [['orders'], 'order'], 'delivery help': [[context.role === 'seller' ? 'shipping-labels' : 'delivery'], 'none'],
        'what is out for delivery': [['orders'], 'none'], 'store pickup help': [['pickup'], 'pickup'], 'how long is store pickup': [['pickup'], 'none'],
        'why is pickup unavailable': [['pickup-availability'], 'pickup'], 'why can\'t i select store pickup': [['pickup-availability'], 'pickup'], 'store pickup not working': [['pickup-availability', 'pickup-settings'], 'pickup'],
        'how do i cancel': [['cancellation'], 'none'], 'cancellation': [['cancellation'], 'none'],
        'payment help': [['payment'], 'payment'], 'my payment failed': [['payment'], 'payment'], 'returns & refunds': [['refunds'], 'refund'], 'return/refund help': [['refunds'], 'refund'],
        'account help': [['account'], 'none'], 'account / store settings': [['account', 'pickup-settings'], 'none'],
        'how do i ship an order': [['shipping-labels'], 'order'], 'how do i mark out for delivery': [['shipping-labels'], 'order'],
        'payment & settlement': [['settlements'], 'none'], 'payment settlement issue': [['settlements'], 'none'], 'product help': [['products'], 'none'],
        'barcode / label help': [['shipping-labels'], 'none'], 'barcode scan problem': [['shipping-labels'], 'none'],
    };
    const match = exact[q];
    return match ? renderAnswer(match[0], match[1], context, match[0].includes('settlements') && /issue|dispute|problem/.test(q)) : undefined;
}
