import {
    PolicyType,
} from "./policy.model.js";


// =========================================
// STATIC POLICY CONTENT
// =========================================

export interface StaticPolicy {
    type: PolicyType;
    title: string;
    content: string;
    version: string;
    active: boolean;
}


export const STATIC_POLICIES:
    Record<
        PolicyType,
        StaticPolicy
    > = {

    // =========================================
    // TERMS
    // =========================================

    terms: {

        type: "terms",

        title:
            "Terms & Conditions",

        version:
            "1.0",

        active:
            true,

        content: `
TERMS & CONDITIONS
नियम एवं शर्तें

1. General
By using this application, you agree to follow these Terms & Conditions. Please read them carefully before placing an order.

1. सामान्य
इस एप्लिकेशन का उपयोग करके आप इन नियम एवं शर्तों से सहमत होते हैं। कृपया ऑर्डर करने से पहले इन्हें ध्यान से पढ़ें।

2. Product Information
We try to provide accurate product names, images, descriptions, prices, stock information and variant details. Minor differences in colour, appearance or packaging may occur.

2. उत्पाद की जानकारी
हम उत्पाद का नाम, फोटो, विवरण, कीमत, स्टॉक और वेरिएंट की सही जानकारी देने का प्रयास करते हैं। रंग, दिखावट या पैकेजिंग में थोड़ा अंतर हो सकता है।

3. Orders
An order is considered successfully placed only after order confirmation is generated by the application. We reserve the right to cancel an order in case of incorrect pricing, unavailable stock, technical issues or other genuine reasons.

3. ऑर्डर
ऑर्डर तभी सफल माना जाएगा जब एप्लिकेशन द्वारा ऑर्डर की पुष्टि की जाए। गलत कीमत, स्टॉक उपलब्ध न होने, तकनीकी समस्या या अन्य उचित कारणों से ऑर्डर रद्द किया जा सकता है।

4. Pricing & Payment
Product prices and applicable delivery charges are displayed during checkout. The customer is responsible for completing the selected payment method.

4. कीमत और भुगतान
उत्पाद की कीमत और लागू डिलीवरी शुल्क चेकआउट के दौरान दिखाए जाते हैं। ग्राहक द्वारा चुनी गई भुगतान विधि के अनुसार भुगतान पूरा करना आवश्यक है।

5. No Return Policy
All products are non-returnable. Once an order has been delivered, the product cannot be returned for a refund.

5. रिटर्न नीति नहीं है
सभी उत्पाद नॉन-रिटर्नेबल हैं। ऑर्डर डिलीवर होने के बाद उत्पाद को वापस करके रिफंड नहीं लिया जा सकता।

6. Replacement Policy
Eligible products can be replaced within 3 days from the date of delivery, subject to the Replacement Policy.

6. रिप्लेसमेंट नीति
योग्य उत्पादों को डिलीवरी की तारीख से 3 दिनों के भीतर Replacement Policy के अनुसार बदला जा सकता है।

7. Same-Day Delivery
Same-day delivery is available only within our supported service area and for eligible orders.

We currently deliver only in Akola, Maharashtra, PIN codes 444001 and 444002.

7. उसी दिन डिलीवरी
Same-day delivery केवल हमारे निर्धारित सेवा क्षेत्र और योग्य ऑर्डर के लिए उपलब्ध है।

हम वर्तमान में केवल अकोला, महाराष्ट्र के पिन कोड 444001 और 444002 में डिलीवरी करते हैं।

8. Customer Responsibility
Customers must provide correct name, mobile number and delivery address.

8. ग्राहक की जिम्मेदारी
ग्राहक को सही नाम, मोबाइल नंबर और डिलीवरी पता देना आवश्यक है।

9. Policy Changes
We may update these Terms & Conditions when required. The latest version available in the application will apply.

9. नीति में बदलाव
आवश्यकता पड़ने पर इन नियम एवं शर्तों में बदलाव किया जा सकता है। एप्लिकेशन में उपलब्ध नवीनतम संस्करण लागू होगा।
        `.trim(),
    },


    // =========================================
    // PRIVACY
    // =========================================

    privacy: {

        type: "privacy",

        title:
            "Privacy Policy",

        version:
            "1.0",

        active:
            true,

        content: `
PRIVACY POLICY
गोपनीयता नीति

Last Updated: 28 August 2026
अंतिम अपडेट: 28 अगस्त 2026

1. Information We Collect
We may collect your name, mobile number, email address, delivery address, order information, account information and other information required to provide our services.

1. हम कौनसी जानकारी एकत्र करते हैं
हम आपका नाम, मोबाइल नंबर, ईमेल पता, डिलीवरी पता, ऑर्डर की जानकारी, अकाउंट की जानकारी और सेवाएं प्रदान करने के लिए आवश्यक अन्य जानकारी एकत्र कर सकते हैं।

2. How We Use Information
We use your information to create and manage your account, process orders, provide delivery, process replacements and cancellations, provide customer support and send important notifications.

2. जानकारी का उपयोग
हम आपकी जानकारी का उपयोग अकाउंट बनाने और प्रबंधित करने, ऑर्डर प्रोसेस करने, डिलीवरी प्रदान करने, Replacement और Cancellation प्रक्रिया, ग्राहक सहायता तथा महत्वपूर्ण नोटिफिकेशन भेजने के लिए करते हैं।

3. Payment Information
Payments may be processed through third-party payment providers. We do not intentionally store complete card or banking credentials on our servers.

3. भुगतान जानकारी
भुगतान third-party payment providers के माध्यम से संसाधित किया जा सकता है। हम पूर्ण कार्ड या बैंकिंग credentials को अपने सर्वर पर जानबूझकर स्टोर नहीं करते।

4. Data Security
We take reasonable measures to protect your information against unauthorized access, misuse, loss or disclosure.

4. डेटा सुरक्षा
हम आपकी जानकारी को unauthorized access, misuse, loss या disclosure से बचाने के लिए उचित सुरक्षा उपाय अपनाते हैं।

5. Account Deletion
Users may request deletion of their account and associated personal information through the account deletion facility provided by the application and designated web resource.

5. अकाउंट डिलीट करना
उपयोगकर्ता एप्लिकेशन में उपलब्ध account deletion सुविधा और designated web resource के माध्यम से अपने अकाउंट और संबंधित व्यक्तिगत जानकारी को हटाने का अनुरोध कर सकते हैं।

6. Changes
This Privacy Policy may be updated from time to time. The latest version will be made available through the application.

6. बदलाव
इस Privacy Policy में समय-समय पर बदलाव किए जा सकते हैं। नवीनतम version एप्लिकेशन में उपलब्ध कराया जाएगा।
        `.trim(),
    },


    // =========================================
    // REPLACEMENT
    // =========================================

    replacement: {

        type:
            "replacement",

        title:
            "Replacement Policy",

        version:
            "1.0",

        active:
            true,

        content: `
REPLACEMENT POLICY
रिप्लेसमेंट नीति

1. No Return
We do not provide returns or refunds for delivered products.

1. कोई रिटर्न नहीं
डिलीवर किए गए उत्पादों के लिए कोई Return या Refund उपलब्ध नहीं है।

2. 3-Day Replacement
Eligible products can be replaced within 3 days from the date of delivery.

2. 3 दिनों के भीतर रिप्लेसमेंट
योग्य उत्पादों को डिलीवरी की तारीख से 3 दिनों के भीतर बदला जा सकता है।

3. Eligible Reasons
Replacement may be considered for damaged, defective, wrong or incorrect-variant products, subject to verification.

3. मान्य कारण
क्षतिग्रस्त, खराब, गलत या गलत वेरिएंट वाले उत्पाद के लिए सत्यापन के बाद Replacement पर विचार किया जा सकता है।

4. Product Condition
The product, packaging, accessories and included items should be available wherever applicable.

4. उत्पाद की स्थिति
जहां लागू हो, उत्पाद, पैकेजिंग, एक्सेसरीज़ और शामिल वस्तुएं उपलब्ध होनी चाहिए।

5. Order Details
Customer must provide the order ID or order details.

5. ऑर्डर की जानकारी
ग्राहक को Order ID या Order Details उपलब्ध करानी होगी।

6. Seller Verification
The seller may inspect the product before approving replacement.

6. विक्रेता द्वारा जांच
Replacement मंजूर करने से पहले विक्रेता उत्पाद की जांच कर सकता है।

7. Replacement Period
A replacement request must be submitted within 3 days from delivery.

7. रिप्लेसमेंट अवधि
Replacement request डिलीवरी के 3 दिनों के भीतर किया जाना आवश्यक है।

8. Seller Visit
Where required, the customer may need to visit the seller's shop with the product and order details.

8. विक्रेता की दुकान
जहां आवश्यक हो, ग्राहक को उत्पाद और Order Details के साथ विक्रेता की दुकान पर जाना पड़ सकता है।
        `.trim(),
    },


    // =========================================
    // CANCELLATION
    // =========================================

    cancellation: {

        type:
            "cancellation",

        title:
            "Cancellation Policy",

        version:
            "1.0",

        active:
            true,

        content: `
CANCELLATION POLICY
कैंसलेशन नीति

1. Order Cancellation
A customer may request cancellation of an order before the order has been shipped.

1. ऑर्डर कैंसलेशन
ग्राहक ऑर्डर के shipped होने से पहले cancellation का अनुरोध कर सकता है।

2. After Shipping
Once an order has been shipped, cancellation may not be available.

2. शिप होने के बाद
ऑर्डर ship हो जाने के बाद cancellation उपलब्ध नहीं हो सकता है।

3. COD Orders
For Cash on Delivery orders, cancellation depends on the current order status. Orders that have already been shipped may not be cancelled.

3. COD ऑर्डर
Cash on Delivery orders का cancellation वर्तमान order status पर निर्भर करता है। जो ऑर्डर पहले ही ship हो चुका है उसे cancel नहीं किया जा सकता।

4. Online Payments
For prepaid orders, any eligible refund resulting from an approved cancellation will be processed according to the applicable payment/refund process.

4. ऑनलाइन भुगतान
Prepaid order के approved cancellation के कारण मिलने वाला eligible refund लागू payment/refund process के अनुसार process किया जाएगा।

5. Seller-Initiated Cancellation
An order may be cancelled by the seller due to unavailable stock, incorrect pricing, technical problems or other genuine reasons.

5. विक्रेता द्वारा कैंसलेशन
स्टॉक उपलब्ध न होने, गलत कीमत, तकनीकी समस्या या अन्य उचित कारणों से seller order cancel कर सकता है।

6. Customer Responsibility
Customers should request cancellation as early as possible before shipment.

6. ग्राहक की जिम्मेदारी
ग्राहक को shipment से पहले जितनी जल्दी हो सके cancellation request करनी चाहिए।
        `.trim(),
    },


    // =========================================
    // SHIPPING
    // =========================================

    shipping: {

        type:
            "shipping",

        title:
            "Shipping Policy",

        version:
            "1.0",

        active:
            true,

        content: `
SHIPPING POLICY
शिपिंग नीति

1. Delivery Area
We currently deliver only in Akola, Maharashtra, PIN codes 444001 and 444002.

1. डिलीवरी क्षेत्र
हम वर्तमान में केवल अकोला, महाराष्ट्र के पिन कोड 444001 और 444002 में डिलीवरी करते हैं।

2. Same-Day Delivery
Same-day delivery is available for eligible orders within our supported service area.

2. उसी दिन डिलीवरी
हमारे निर्धारित सेवा क्षेत्र में योग्य ऑर्डर के लिए उसी दिन डिलीवरी उपलब्ध है।

3. Delivery Charges
Applicable delivery charges are displayed during checkout.

3. डिलीवरी शुल्क
लागू डिलीवरी शुल्क checkout के दौरान दिखाया जाता है।

4. Delivery Address
Customers must provide a complete and accurate delivery address and valid mobile number.

4. डिलीवरी पता
ग्राहक को पूरा और सही delivery address तथा valid mobile number देना आवश्यक है।

5. Delivery Delays
Delivery may be delayed because of traffic, weather, product availability, operational issues or other circumstances beyond our reasonable control.

5. डिलीवरी में देरी
Traffic, मौसम, product availability, operational issues या अन्य परिस्थितियों के कारण delivery में देरी हो सकती है।

6. Failed Delivery
If delivery cannot be completed because of an incorrect address, unavailable customer or other customer-related issue, the order may require further coordination with the seller.

6. असफल डिलीवरी
गलत पता, ग्राहक उपलब्ध न होने या अन्य ग्राहक संबंधी कारणों से delivery पूरी नहीं हो पाने पर seller के साथ आगे coordination की आवश्यकता हो सकती है।
        `.trim(),
    },


    // =========================================
    // REFUND
    // =========================================

    refund: {

        type:
            "refund",

        title:
            "Refund Policy",

        version:
            "1.0",

        active:
            true,

        content: `
REFUND POLICY
रिफंड नीति

Our products are generally non-returnable. Any refund, where applicable, will be processed only according to the approved cancellation, payment or other applicable process.

हमारे उत्पाद सामान्यतः non-returnable हैं। जहां लागू हो, refund केवल approved cancellation, payment या अन्य applicable process के अनुसार ही किया जाएगा।
        `.trim(),
    },
};